### ISSUE TITLE
How to use the code ?

### ISSUE THREAD

**Issue by NuiMrme** [shichaoy/pop_up_image#4]
Hello Shichaoy,
I successfully compiled the code. A nice 3d mesh appeared etc. However I don't see how can I use the code on my own images, I would appreciate if you could explain a little how can I use the code to try your method on my data.

Thanks

**Comment by shichaoy** [comment]
hi, NuiMrme. Thanks for the interest. The code basically requires an RGB image and ground labelled image, examples shown in pop_up_wall/data/. In the main file, you also need to provide calibration and camera pose (at least roll, pitch, height).    To get ground labeling, you can simply use many public algorithms.  We can discuss more if you need help on this.

**Comment by NuiMrme** [comment]
Thanks for your reply. My bad ! for some reason I didn't see that folder. I'm only interested in the pop-up part. I have an outdoor sequence of a river,  I have my calibration based on Auto-Calibration (might not be perfect) and a label image based on segmentation and manual correction.  I don't have camera pose. The hope is to be able to popup a 3D model in which the river is the ground and the walls are whatever is vertical on the banks (walls, banks ,bridges etc...). First attemp using my calibration and the pose assumed in your code reconstructed only the river. It printed out "only one good plane is found". At some point in your article you mentioned that different poses might pop-up different reconstructions. So I'm going to experiment with thepose to see if I can have at least a second wall plane. My question is there is any threshold somewhere in the code that decides if this is a good plane or not. 

Thanks again

**Comment by NuiMrme** [comment]
Well , I just did the above and it worked like what I really hoped for. Now I'm going to read in details your publications to fully understand it. Thanks a lot
