### ISSUE TITLE
Ground plane segmentation

### ISSUE THREAD

**Issue by felixem** [shichaoy/pop_up_image#6]
Hello. I'm checking your work and it is really impressive. Now, I'm testing with my own images, so I wonder if the ground plane segmentation network used in your papers is published somewhere.
Greetings.

**Comment by shichaoy** [comment]
Hi, thanks. My ground segmentation part is quite outdated learning framework and I didn't used anymore. I later just use other public algorithms trained in indoor environments, such as Segnet.

**Comment by felixem** [comment]
Ok. Thank you so much.
